*--------------------------------------------------------------------
* Microsoft ADO
*
* (c) 1997 Microsoft Corporation.  All Rights Reserved.
*
*
*
* ADO constants include file for Visual FoxPro
*
*--------------------------------------------------------------------

*---- CursorTypeEnum Values ----
#DEFINE ADOPENFORWARDONLY		0
#DEFINE ADOPENKEYSET			1
#DEFINE ADOPENDYNAMIC			2
#DEFINE ADOPENSTATIC			3

*---- CursorOptionEnum Values ----
#DEFINE ADHOLDRECORDS		&H00000100
#DEFINE ADMOVEPREVIOUS		&H00000200
#DEFINE ADADDNEW			&H01000400
#DEFINE ADDELETE			&H01000800
#DEFINE ADUPDATE			&H01008000
#DEFINE ADBOOKMARK			&H00002000
#DEFINE ADAPPROXPOSITION	&H00004000
#DEFINE ADUPDATEBATCH		&H00010000
#DEFINE ADRESYNC			&H00020000
#DEFINE ADNOTIFY			&H00040000

*---- LockTypeEnum Values ----
#DEFINE ADLOCKREADONLY			1
#DEFINE ADLOCKPESSIMISTIC		2
#DEFINE ADLOCKOPTIMISTIC		3
#DEFINE ADLOCKBATCHOPTIMISTIC	4

*---- ExecuteOptionEnum Values ----
#DEFINE ADRUNASYNC		&H00000010

*---- ObjectStateEnum Values ----
#DEFINE ADSTATECLOSED		&H00000000
#DEFINE ADSTATEOPEN			&H00000001
#DEFINE ADSTATECONNECTING	&H00000002
#DEFINE ADSTATEEXECUTING	&H00000004

*---- CursorLocationEnum Values ----
#DEFINE ADUSESERVER		2
#DEFINE ADUSECLIENT		3

*---- DataTypeEnum Values ----
#DEFINE ADEMPTY					0
#DEFINE ADTINYINT				16
#DEFINE ADSMALLINT				2
#DEFINE ADINTEGER				3
#DEFINE ADBIGINT				20
#DEFINE ADUNSIGNEDTINYINT		17
#DEFINE ADUNSIGNEDSMALLINT		18
#DEFINE ADUNSIGNEDINT			19
#DEFINE ADUNSIGNEDBIGINT		21
#DEFINE ADSINGLE				4
#DEFINE ADDOUBLE				5
#DEFINE ADCURRENCY				6
#DEFINE ADDECIMAL				14
#DEFINE ADNUMERIC				131
#DEFINE ADBOOLEAN				11
#DEFINE ADERROR					10
#DEFINE ADUSERDEFINED			132
#DEFINE ADVARIANT				12
#DEFINE ADIDISPATCH				9
#DEFINE ADIUNKNOWN				13
#DEFINE ADGUID					72
#DEFINE ADDATE					7
#DEFINE ADDBDATE				133
#DEFINE ADDBTIME				134
#DEFINE ADDBTIMESTAMP			135
#DEFINE ADBSTR					8
#DEFINE ADCHAR					129
#DEFINE ADVARCHAR				200
#DEFINE ADLONGVARCHAR			201
#DEFINE ADWCHAR					130
#DEFINE ADVARWCHAR				202
#DEFINE ADLONGVARWCHAR			203
#DEFINE ADBINARY				128
#DEFINE ADVARBINARY				204
#DEFINE ADLONGVARBINARY			205
#DEFINE ADCHAPTER				136

*---- FieldAttributeEnum Values ----
#DEFINE ADFLDMAYDEFER			&H00000002
#DEFINE ADFLDUPDATABLE			&H00000004
#DEFINE ADFLDUNKNOWNUPDATABLE	&H00000008
#DEFINE ADFLDFIXED				&H00000010
#DEFINE ADFLDISNULLABLE			&H00000020
#DEFINE ADFLDMAYBENULL			&H00000040
#DEFINE ADFLDLONG				&H00000080
#DEFINE ADFLDROWID				&H00000100
#DEFINE ADFLDROWVERSION			&H00000200
#DEFINE ADFLDCACHEDEFERRED		&H00001000

*---- EditModeEnum Values ----
#DEFINE ADEDITNONE				&H0000
#DEFINE ADEDITINPROGRESS		&H0001
#DEFINE ADEDITADD				&H0002
#DEFINE ADEDITDELETE			&H0004

*---- RecordStatusEnum Values ----
#DEFINE ADRECOK						&H0000000
#DEFINE ADRECNEW					&H0000001
#DEFINE ADRECMODIFIED				&H0000002
#DEFINE ADRECDELETED				&H0000004
#DEFINE ADRECUNMODIFIED				&H0000008
#DEFINE ADRECINVALID				&H0000010
#DEFINE ADRECMULTIPLECHANGES		&H0000040
#DEFINE ADRECPENDINGCHANGES			&H0000080
#DEFINE ADRECCANCELED				&H0000100
#DEFINE ADRECCANTRELEASE			&H0000400
#DEFINE ADRECCONCURRENCYVIOLATION	&H0000800
#DEFINE ADRECINTEGRITYVIOLATION		&H0001000
#DEFINE ADRECMAXCHANGESEXCEEDED		&H0002000
#DEFINE ADRECOBJECTOPEN				&H0004000
#DEFINE ADRECOUTOFMEMORY			&H0008000
#DEFINE ADRECPERMISSIONDENIED		&H0010000
#DEFINE ADRECSCHEMAVIOLATION		&H0020000
#DEFINE ADRECDBDELETED				&H0040000

*---- GetRowsOptionEnum Values ----
#DEFINE ADGETROWSREST		-1

*---- PositionEnum Values ----
#DEFINE ADPOSUNKNOWN	-1
#DEFINE ADPOSBOF		-2
#DEFINE ADPOSEOF		-3

*---- BookmarkConstants Values ----
#DEFINE ADBOOKMARKCURRENT	0.0
#DEFINE ADBOOKMARKFIRST		1.0
#DEFINE ADBOOKMARKLAST		2.0

*---- MarshalOptionsEnum Values ----
#DEFINE ADMARSHALALL			0
#DEFINE ADMARSHALMODIFIEDONLY	1

*---- AffectEnum Values ----
#DEFINE ADAFFECTCURRENT		1
#DEFINE ADAFFECTGROUP		2
#DEFINE ADAFFECTALL			3

*---- FilterGroupEnum Values ----
#DEFINE ADFILTERNONE				0
#DEFINE ADFILTERPENDINGRECORDS		1
#DEFINE ADFILTERAFFECTEDRECORDS		2
#DEFINE ADFILTERFETCHEDRECORDS		3
#DEFINE ADFILTERPREDICATE			4

*---- SearchDirectionEnum Values ----
#DEFINE ADSEARCHFORWARD		1
#DEFINE ADSEARCHBACKWARD	-1

*---- PersistFormatEnum Values ----
#DEFINE ADPERSISTADTG		0
#DEFINE ADPERSISTXML		1
#DEFINE ADPERSISTHTML		2

*---- SaveOptionEnum Values ----
#DEFINE ADSAVEOVERWRITE		0
#DEFINE ADSAVEFAILIFEXIST		

*---- ConnectPromptEnum Values ----
#DEFINE ADPROMPTALWAYS				1
#DEFINE ADPROMPTCOMPLETE			2
#DEFINE ADPROMPTCOMPLETEREQUIRED	3
#DEFINE ADPROMPTNEVER				4

*---- ConnectModeEnum Values ----
#DEFINE ADMODEUNKNOWN			0
#DEFINE ADMODEREAD				1
#DEFINE ADMODEWRITE				2
#DEFINE ADMODEREADWRITE			3
#DEFINE ADMODESHAREDENYREAD		4
#DEFINE ADMODESHAREDENYWRITE	8
#DEFINE ADMODESHAREEXCLUSIVE	&HC
#DEFINE ADMODESHAREDENYNONE		&H10

*---- IsolationLevelEnum Values ----
#DEFINE ADXACTUNSPECIFIED		&HFFFFFFFF
#DEFINE ADXACTCHAOS				&H00000010
#DEFINE ADXACTREADUNCOMMITTED	&H00000100
#DEFINE ADXACTBROWSE			&H00000100
#DEFINE ADXACTCURSORSTABILITY	&H00001000
#DEFINE ADXACTREADCOMMITTED		&H00001000
#DEFINE ADXACTREPEATABLEREAD	&H00010000
#DEFINE ADXACTSERIALIZABLE		&H00100000
#DEFINE ADXACTISOLATED			&H00100000

*---- XactAttributeEnum Values ----
#DEFINE ADXACTCOMMITRETAINING	&H00020000
#DEFINE ADXACTABORTRETAINING	&H00040000

*---- PropertyAttributesEnum Values ----
#DEFINE ADPROPNOTSUPPORTED		&H0000
#DEFINE ADPROPREQUIRED			&H0001
#DEFINE ADPROPOPTIONAL			&H0002
#DEFINE ADPROPREAD				&H0200
#DEFINE ADPROPWRITE				&H0400

*---- ErrorValueEnum Values ----
#DEFINE ADERRINVALIDARGUMENT		&HBB9
#DEFINE ADERRNOCURRENTRECORD		&HBCD
#DEFINE ADERRILLEGALOPERATION		&HC93
#DEFINE ADERRINTRANSACTION			&HCAE
#DEFINE ADERRFEATURENOTAVAILABLE	&HCB3
#DEFINE ADERRITEMNOTFOUND			&HCC1
#DEFINE ADERROBJECTINCOLLECTION		&HD27
#DEFINE ADERROBJECTNOTSET			&HD5C
#DEFINE ADERRDATACONVERSION			&HD5D
#DEFINE ADERROBJECTCLOSED			&HE78
#DEFINE ADERROBJECTOPEN				&HE79
#DEFINE ADERRPROVIDERNOTFOUND		&HE7A
#DEFINE ADERRBOUNDTOCOMMAND			&HE7B
#DEFINE ADERRINVALIDPARAMINFO		&HE7C
#DEFINE ADERRINVALIDCONNECTION		&HE7D
#DEFINE ADERRNOTREENTRANT			&HE7E
#DEFINE ADERRSTILLEXECUTING			&HE7F
#DEFINE ADERROPERATIONCANCELLED		&HE80
#DEFINE ADERRSTILLCONNECTING		&HE81
#DEFINE ADERRINVALIDTRANSACTION		&HE82

*---- ParameterAttributesEnum Values ----
#DEFINE ADPARAMSIGNED		&H0010
#DEFINE ADPARAMNULLABLE		&H0040
#DEFINE ADPARAMLONG			&H0080

*---- ParameterDirectionEnum Values ----
#DEFINE ADPARAMUNKNOWN		&H0000
#DEFINE ADPARAMINPUT		&H0001
#DEFINE ADPARAMOUTPUT		&H0002
#DEFINE ADPARAMINPUTOUTPUT	&H0003
#DEFINE ADPARAMRETURNVALUE	&H0004

*---- CommandTypeEnum Values ----
#DEFINE ADCMDUNKNOWN		&H0008
#DEFINE ADCMDTEXT			&H0001
#DEFINE ADCMDTABLE			&H0002
#DEFINE ADCMDSTOREDPROC		&H0004
#DEFINE ADCMDFILE			&H0020

*---- EventStatusEnum Values ----
#DEFINE ADSTATUSOK				&H0000001
#DEFINE ADSTATUSERRORSOCCURRED	&H0000002
#DEFINE ADSTATUSCANTDENY		&H0000003
#DEFINE ADSTATUSCANCEL			&H0000004
#DEFINE ADSTATUSUNWANTEDEVENT	&H0000005

*---- EventReasonEnum Values ----
#DEFINE ADRSNADDNEW			1
#DEFINE ADRSNDELETE			2
#DEFINE ADRSNUPDATE			3
#DEFINE ADRSNUNDOUPDATE		4
#DEFINE ADRSNUNDOADDNEW		5
#DEFINE ADRSNUNDODELETE		6
#DEFINE ADRSNREQUERY		7
#DEFINE ADRSNRESYNCH		8
#DEFINE ADRSNCLOSE			9
#DEFINE ADRSNMOVE			10
#DEFINE ADRSNFIRSTCHANGE	11
#DEFINE ADRSNMOVEFIRST		12
#DEFINE ADRSNMOVENEXT		13
#DEFINE ADRSNMOVEPREVIOUS	14
#DEFINE ADRSNMOVELAST		15

*---- SchemaEnum Values ----
#DEFINE ADSCHEMAPROVIDERSPECIFIC		-1
#DEFINE ADSCHEMAASSERTS					0
#DEFINE ADSCHEMACATALOGS				1
#DEFINE ADSCHEMACHARACTERSETS			2
#DEFINE ADSCHEMACOLLATIONS				3
#DEFINE ADSCHEMACOLUMNS					4
#DEFINE ADSCHEMACHECKCONSTRAINTS		5
#DEFINE ADSCHEMACONSTRAINTCOLUMNUSAGE	6
#DEFINE ADSCHEMACONSTRAINTTABLEUSAGE	7
#DEFINE ADSCHEMAKEYCOLUMNUSAGE			8
#DEFINE ADSCHEMAREFERENTIALCONTRAINTS	9
#DEFINE ADSCHEMATABLECONSTRAINTS		10
#DEFINE ADSCHEMACOLUMNSDOMAINUSAGE		11
#DEFINE ADSCHEMAINDEXES					12
#DEFINE ADSCHEMACOLUMNPRIVILEGES		13
#DEFINE ADSCHEMATABLEPRIVILEGES			14
#DEFINE ADSCHEMAUSAGEPRIVILEGES			15
#DEFINE ADSCHEMAPROCEDURES				16
#DEFINE ADSCHEMASCHEMATA				17
#DEFINE ADSCHEMASQLLANGUAGES			18
#DEFINE ADSCHEMASTATISTICS				19
#DEFINE ADSCHEMATABLES					20
#DEFINE ADSCHEMATRANSLATIONS			21
#DEFINE ADSCHEMAPROVIDERTYPES			22
#DEFINE ADSCHEMAVIEWS					23
#DEFINE ADSCHEMAVIEWCOLUMNUSAGE			24
#DEFINE ADSCHEMAVIEWTABLEUSAGE			25
#DEFINE ADSCHEMAPROCEDUREPARAMETERS		26
#DEFINE ADSCHEMAFOREIGNKEYS				27
#DEFINE ADSCHEMAPRIMARYKEYS				28
#DEFINE ADSCHEMAPROCEDURECOLUMNS		29
#DEFINE ADSCHEMADBINFOKEYWORDS			30
#DEFINE ADSCHEMADBINFOLITERALS			31
