* COVERAGE.H

*&* Coverage character constants for log and parsing:
#INCLUDE COV_CHAR.H

*&* Coverage localized strings (may use some constants above):
#INCLUDE COV_LOCS.H

*&* Coverage common dialog component constants:
#INCLUDE COV_DLGS.H

*&* Coverage specs & requirements:
#INCLUDE COV_SPEC.H

*&* Coverage registry object constants:
#INCLUDE COV_REGS.H

*&* Coverage tune-able options:
#INCLUDE COV_TUNE.H

