PROC JUSTSTEM
PROC JUSTEXT
PROC MKDIR
PROC WBHELP
PROC WBSETENVIRONMENT
PROC FXSETTYPE
PROC GETCLICKS
PROC REMOVEOBJECT
PROC WRITEEXPRESSION
PROC WRITEMETHOD

PUBLIC WBACONTROL[1]
PUBLIC WBAALLDATA[1]
PUBLIC WBADATA[1]
PUBLIC WBAENVIR[1]
PUBLIC APARMS[1]
PUBLIC AGLOBALS[1]
PUBLIC AFLDDATA[1]
PUBLIC AAFIELDDATA[1]
PUBLIC ATMPGLOBALS[1]
PUBLIC AWIZFIELDS[1]
PUBLIC ALISTARRAY[1]
PUBLIC WBACOLS[1]

PUBLIC REGOPENKEY[1]
PUBLIC REGENUMVALUE[1]
PUBLIC REGQUERYVALUEEX[1]
PUBLIC REGSETVALUEEX[1]
