&& don't call this function ...
&& it's only purpose is to make the function names visible for compilation
&& the functions are DECLARE'd inside the library automatically
FUNCTION VFP2CDummyProc
DECLARE WriteChar IN vfp2c32.fll INTEGER, STRING
DECLARE WritePChar IN vfp2c32.fll INTEGER, STRING
DECLARE WriteInt8 IN vfp2c32.fll INTEGER, INTEGER
DECLARE WritePInt8 IN vfp2c32.fll INTEGER, INTEGER
DECLARE WriteUInt8 IN vfp2c32.fll INTEGER, INTEGER
DECLARE WritePUInt8 IN vfp2c32.fll INTEGER, INTEGER
DECLARE WriteShort IN vfp2c32.fll INTEGER, SHORT	
DECLARE WritePShort IN vfp2c32.fll INTEGER, SHORT
DECLARE WriteUShort IN vfp2c32.fll INTEGER, SHORT
DECLARE WritePUShort IN vfp2c32.fll INTEGER, SHORT
DECLARE WriteInt IN vfp2c32.fll INTEGER, INTEGER
DECLARE WritePInt IN vfp2c32.fll INTEGER, INTEGER
DECLARE WriteUInt IN vfp2c32.fll INTEGER, INTEGER
DECLARE WritePUInt IN vfp2c32.fll INTEGER, INTEGER
DECLARE WritePointer IN vfp2c32.fll INTEGER, INTEGER
DECLARE WritePPointer IN vfp2c32.fll INTEGER, INTEGER
DECLARE WriteFloat IN vfp2c32.fll INTEGER, SINGLE
DECLARE WritePFloat IN vfp2c32.fll INTEGER, SINGLE
DECLARE WriteDouble IN vfp2c32.fll INTEGER, DOUBLE
DECLARE WritePDouble IN vfp2c32.fll INTEGER, DOUBLE
DECLARE SHORT ReadInt8 IN vfp2c32.fll INTEGER
DECLARE SHORT ReadPInt8 IN vfp2c32.fll INTEGER
DECLARE SHORT ReadUInt8 IN vfp2c32.fll INTEGER
DECLARE SHORT ReadPUInt8 IN vfp2c32.fll INTEGER
DECLARE SHORT ReadShort IN vfp2c32.fll INTEGER
DECLARE SHORT ReadPShort IN vfp2c32.fll INTEGER
DECLARE INTEGER ReadUShort IN vfp2c32.fll INTEGER
DECLARE INTEGER ReadPUShort IN vfp2c32.fll INTEGER
DECLARE INTEGER ReadInt IN vfp2c32.fll INTEGER
DECLARE INTEGER ReadPInt IN vfp2c32.fll INTEGER
DECLARE SINGLE ReadFloat IN vfp2c32.fll INTEGER
DECLARE SINGLE ReadPFloat IN vfp2c32.fll INTEGER
DECLARE DOUBLE ReadDouble IN vfp2c32.fll INTEGER
DECLARE DOUBLE ReadPDouble IN vfp2c32.fll INTEGER
ENDFUNC

