#DEFINE E_STRING1_LOC "Could not find FDKEYWRD table"
#DEFINE E_STRING2_LOC "Could not find FD3.FLL library"
#DEFINE WHEREIS_LOC	 "Where is "

#DEFINE EDENV_FILENAME      1
#DEFINE EDENV_LENGTH		2
#DEFINE EDENV_READONLY		12
#DEFINE EDENV_SELSTART		17
#DEFINE EDENV_SELEND		18

#define TAB					CHR(9)